apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This file assembles the "extensions" install
resources:
# 1. Start with the ENTIRE base install
- ./ # This loads k8s/kustomization.yaml

# 2. Add the static extensions
- overlays/extensions

# 3. Add the generated extensions files
- extensions-rbac.generated.yaml
- crds/extensions.agents.x-k8s.io_sandboxclaims.yaml
- crds/extensions.agents.x-k8s.io_sandboxtemplates.yaml
- crds/extensions.agents.x-k8s.io_sandboxwarmpools.yaml